version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php73
    volumes:
        - ./public_html:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    container_name: mysql8
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kcs_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
        - 6033:3306
